### ISSUE TITLE
make codegen vs make spec

### ISSUE THREAD

**Issue by mrcdb** [hirose31/connexion-tiny-petstore#3]
Hi, thanks for this very valuable example on Connexion! I am a bit puzzled by the `make codegen` and `make spec` commands in the Makefile. Both re-create models and controllers starting from the OpenAPI YAML, but the first also generates test-cases and some other files....

Which one should I use if I am using a a totally different OpenAPI spec ? Thanks!

**Comment by hirose31** [comment]
Hi, thanks for reading my tiny-petstore :D

I don't edit `tiny_petstore/openapi/openapi.yaml` which is just generated by openapi-generator-cli from `tiny-petstore.yaml`. When I edit `tiny-petstore.yaml`, then do `make spec` to generate `openapi.yaml`.

`make codegen` is for generating all files (codes, spec ...) at first, so you may not need to do `make codegen`.

**Comment by mrcdb** [comment]
Thanks!
